trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: self
- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    workingDirectory: 'UiTestFrameworkFrNumbersQuiz'
    testRunTitle: 'Production - UI Test'